<a href="https://colab.research.google.com/github/tusharmaurya267/Python_basic/blob/main/Function%2CNumpy%2CPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
def hello():
  print("hello world")

In [3]:
hello()

hello world


In [4]:
def add10(x):
  return 10+x

In [5]:
add10(5)

15

In [ ]:
# LAMBDA FUNCTION

In [9]:
store=lambda x : x*x*x
print(store(3))

27


In [11]:
l1=[2,5,8,10,14,15,17,23,27,28,30,31,35,38]
new_list=list(filter((lambda x: x%2!=0), l1))
print(new_list)

[5, 15, 17, 23, 27, 31, 35]


In [13]:
l1=[2,5,8,10,14,15,17,23,27,28,30,31,35,38]
new_list=list(map((lambda x: x*2), l1))
print(new_list)

[4, 10, 16, 20, 28, 30, 34, 46, 54, 56, 60, 62, 70, 76]


In [16]:
from functools import reduce
l1=[2,5,8,10,14,15,17,23,27,28,30,31,35,38]
new_list=reduce((lambda x,y : x+y ), l1)
print(new_list)

283


In [17]:
# CODE FOR FACTORIAL USING RECURSION

def factorial(n):
  if(n==0):
    return 1
  else:
    return factorial(n-1)*n


In [19]:
print(factorial(4))

24


In [31]:
# CODE FOR SET AND LIST USES

def listuse(n):
  l1=[]
  print("Enter n numbers:  ")
  for i in range(n):
    x=int(input())
    l1.append(x)
  
  new_n=len(l1)
  for i in range(new_n):
    print(l1[i]+5)

def setuse(n):
  s1=set()
  print("Enter n numbers: ")
  for i in range(n):
    x=int(input())
    s1.add(x)
  
  new_n=len(s1)
  for i in range(new_n):
    print(i+10)


In [21]:
listuse(4)


Enter n numbers:  
1
2
3
4
5
6
7
8
9
10
6
7
8
9
10
11
12
13
14
15


In [32]:
setuse(4)

Enter n numbers: 
1
2
3
4
5
6
7
8


In [33]:
# NUMPY

In [35]:
import numpy as np

In [36]:
l1=[1,2,3,4,5]
l2=[11,12,13,14,15,16,17]

In [37]:
l1=np.array(l1)
l2=np.array(l2)

In [38]:
l1

array([1, 2, 3, 4, 5])

In [39]:
type(l1)

numpy.ndarray

In [44]:
l3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(l3[2,1])

8


In [45]:
print(l3[2][1])

6


In [47]:
print(l3[2,:])

[7 8 9]


In [48]:
print(l3[:,2])

[3 6 9]


In [49]:
l1[2:4]

array([3, 4])

In [50]:
l1[2:]

array([3, 4, 5])

In [51]:
l1[:]

array([1, 2, 3, 4, 5])

In [54]:
l3[1:2,1:3]

array([[5, 6]])

In [56]:
a1=([100,200,300,400,500])
a2=np.arange(5)
a2

array([0, 1, 2, 3, 4])

In [57]:
a1+a2

array([100, 201, 302, 403, 504])

In [59]:
a2*4

array([ 0,  4,  8, 12, 16])

In [60]:
a2**3

array([ 0,  1,  8, 27, 64])

In [62]:
a3=np.array([20,30,40,50,60])
new_array= a3>=40
new_array

array([False, False,  True,  True,  True])

In [64]:
a3[new_array]

array([40, 50, 60])

PANDAS

In [2]:
import pandas as pd

In [3]:
num=range(1,100,5)
pd.Series(num)

0      1
1      6
2     11
3     16
4     21
5     26
6     31
7     36
8     41
9     46
10    51
11    56
12    61
13    66
14    71
15    76
16    81
17    86
18    91
19    96
dtype: int64

In [6]:
string='hi', 'how', 'are', 'you'
pd.Series(string)

0     hi
1    how
2    are
3    you
dtype: object

In [5]:
pd.Series([345, 'aaru' , 23,6 , 'lohan'])

0      345
1     aaru
2       23
3        6
4    lohan
dtype: object

In [7]:
marks=[60,70,80,85]
subject=['hindi','english','maths','science']
pd.Series(marks,index=subject)

hindi      60
english    70
maths      80
science    85
dtype: int64

In [8]:
data={'maths':70 , 'english':75 , 'hindi':85 , 'science':73}
pd.Series(data)

maths      70
english    75
hindi      85
science    73
dtype: int64

In [9]:
subject=['maths','english','arts','hindi']
pd.Series(data,index=subject)

maths      70.0
english    75.0
arts        NaN
hindi      85.0
dtype: float64

In [41]:
data={'subject' : ['maths','english','arts','hindi','science','Social Science'] ,
      'marks' : (50,65,70,75,80,83),
      'CGPA' : [2.1, 4.0, 5.9, 8.1, 8.5, 6.8]}
df=pd.DataFrame(data)
df

subject  marks  CGPA
0           maths     50   2.1
1         english     65   4.0
2            arts     70   5.9
3           hindi     75   8.1
4         science     80   8.5
5  Social Science     83   6.8

In [35]:
# df2=pd.DataFrame(['subject','marks','CGPA'], index=['subject','marks','CGPA'])
df1=pd.DataFrame(data).T
df1

0       1          2          3        4
Username    booker23  grey44  johnson81  jenkins46  smith79
Identifier    129012  172070     814081     469346   798045
First name    Rachel   Laura      Craid       Mary    Jamie
Last name     Booker    Grey    Johnson    Jenkins    Smith

In [42]:
data=pd.read_csv("username.csv")

In [43]:
type(data)

pandas.core.frame.DataFrame

In [44]:
print(data)

    Username  Identifier First name Last name
0   booker23      129012     Rachel    Booker
1     grey44      172070      Laura      Grey
2  johnson81      814081      Craid   Johnson
3  jenkins46      469346       Mary   Jenkins
4    smith79      798045      Jamie     Smith


In [45]:
data.head()

Username  Identifier First name Last name
0   booker23      129012     Rachel    Booker
1     grey44      172070      Laura      Grey
2  johnson81      814081      Craid   Johnson
3  jenkins46      469346       Mary   Jenkins
4    smith79      798045      Jamie     Smith

In [46]:
data.head(3)

Username  Identifier First name Last name
0   booker23      129012     Rachel    Booker
1     grey44      172070      Laura      Grey
2  johnson81      814081      Craid   Johnson

In [47]:
data.tail()

Username  Identifier First name Last name
0   booker23      129012     Rachel    Booker
1     grey44      172070      Laura      Grey
2  johnson81      814081      Craid   Johnson
3  jenkins46      469346       Mary   Jenkins
4    smith79      798045      Jamie     Smith

In [48]:
data.shape

(5, 4)

In [49]:
data.dtypes

Username      object
Identifier     int64
First name    object
Last name     object
dtype: object

In [50]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Username    5 non-null      object
 1   Identifier  5 non-null      int64 
 2   First name  5 non-null      object
 3   Last name   5 non-null      object
dtypes: int64(1), object(3)
memory usage: 288.0+ bytes


In [51]:
type(data["Username"])

pandas.core.series.Series

In [53]:
data["BMI"]=data["Identifier"]-100000*2
data

Username  Identifier First name Last name     BMI
0   booker23      129012     Rachel    Booker  -70988
1     grey44      172070      Laura      Grey  -27930
2  johnson81      814081      Craid   Johnson  614081
3  jenkins46      469346       Mary   Jenkins  269346
4    smith79      798045      Jamie     Smith  598045

In [55]:
data_copy=data.copy()
data_copy.loc[5]=['lohan12',456423,'lohan','kevin',232345]

In [70]:
data_copy.loc[6]=['briyan12',459543,'briyan','paul',232345]

In [71]:
data_copy

Username  Identifier First name Last name     BMI
0   booker23      129012     Rachel    Booker  -70988
1     grey44      172070      Laura      Grey  -27930
2  johnson81      814081      Craid   Johnson  614081
3  jenkins46      469346       Mary   Jenkins  269346
4    smith79      798045      Jamie     Smith  598045
5   briyan12      459543     briyan      paul  232345
6   briyan12      459543     briyan      paul  232345

In [77]:
data=data_copy

In [78]:
data.iloc[3]

Username      jenkins46
Identifier       469346
First name         Mary
Last name       Jenkins
BMI              269346
Name: 3, dtype: object

In [79]:
data.iloc[2:5]

Username  Identifier First name Last name     BMI
2  johnson81      814081      Craid   Johnson  614081
3  jenkins46      469346       Mary   Jenkins  269346
4    smith79      798045      Jamie     Smith  598045

In [80]:
data.iloc[:,2]

0    Rachel
1     Laura
2     Craid
3      Mary
4     Jamie
5    briyan
6    briyan
Name: First name, dtype: object

In [81]:
data.sort_values('BMI')

Username  Identifier First name Last name     BMI
0   booker23      129012     Rachel    Booker  -70988
1     grey44      172070      Laura      Grey  -27930
5   briyan12      459543     briyan      paul  232345
6   briyan12      459543     briyan      paul  232345
3  jenkins46      469346       Mary   Jenkins  269346
4    smith79      798045      Jamie     Smith  598045
2  johnson81      814081      Craid   Johnson  614081

In [82]:
data['BMI_rank']=data['BMI'].rank(ascending=0,method='min')
data

Username  Identifier First name Last name     BMI  BMI_rank
0   booker23      129012     Rachel    Booker  -70988       7.0
1     grey44      172070      Laura      Grey  -27930       6.0
2  johnson81      814081      Craid   Johnson  614081       1.0
3  jenkins46      469346       Mary   Jenkins  269346       3.0
4    smith79      798045      Jamie     Smith  598045       2.0
5   briyan12      459543     briyan      paul  232345       4.0
6   briyan12      459543     briyan      paul  232345       4.0

In [84]:
data['BMI_rank']=data['BMI'].rank(ascending=0,method='dense')

In [85]:
data.isnull().sum()

Username      0
Identifier    0
First name    0
Last name     0
BMI           0
BMI_rank      0
dtype: int64

In [90]:
my_df1={'Product_id' :[1,2,3,4,5],
        'Food_product' :['cake','biscuit','namkeen','pastry','burger'],
        'Brand_product' :['Baskin robbins' , 'walnut' , 'bikaner' , 'danbro' , 'Peach']}

my_df2={'Product_id' :[4,5,2,3,1],
        'Food_product' :['bsicuit','burger','cake','namkeen','pastry'],
        'Brand_product' :['walnut' , 'bikaner' , 'Baskin robbins' , 'Peach' , 'danbro']}

my_df1=pd.DataFrame(my_df1)
my_df2=pd.DataFrame(my_df2)
pd.merge(my_df1 , my_df2 , on=['Product_id','Food_product'],how='inner')

Product_id Food_product Brand_product_x Brand_product_y
0           3      namkeen         bikaner           Peach
1           5       burger           Peach         bikaner

In [91]:
pd.merge(my_df1 , my_df2 , on=['Product_id','Food_product'],how='outer')

Product_id Food_product Brand_product_x Brand_product_y
0           1         cake  Baskin robbins             NaN
1           2      biscuit          walnut             NaN
2           3      namkeen         bikaner           Peach
3           4       pastry          danbro             NaN
4           5       burger           Peach         bikaner
5           4      bsicuit             NaN          walnut
6           2         cake             NaN  Baskin robbins
7           1       pastry             NaN          danbro

In [92]:
pd.merge(my_df1 , my_df2 , on=['Product_id','Food_product'],how='left')

Product_id Food_product Brand_product_x Brand_product_y
0           1         cake  Baskin robbins             NaN
1           2      biscuit          walnut             NaN
2           3      namkeen         bikaner           Peach
3           4       pastry          danbro             NaN
4           5       burger           Peach         bikaner