<a href="https://colab.research.google.com/github/tusharmaurya267/Python_basic/blob/main/python_data_analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**

In [1]:
import numpy as np

In [25]:
# 1D array of integer
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(size(arr1))
print(arr1.size)
print(arr1.shape)
print(arr1.dtype)
print(arr1.transpose())

[1 2 3 4 5]
<class 'numpy.ndarray'>
5
5
(5,)
int64
[1 2 3 4 5]


In [26]:
# 2D array of integer
arr2 = np.array([[1,2,3,4],[5,6,7.1,8]])
print(arr2)
print(size(arr2))
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)
print(arr2.transpose())

[[1.  2.  3.  4. ]
 [5.  6.  7.1 8. ]]
8
8
(2, 4)
float64
[[1.  5. ]
 [2.  6. ]
 [3.  7.1]
 [4.  8. ]]


In [42]:
# 1D array of characters
arr2 = np.array(['a','b',3,'d'])
print(arr2)
print(size(arr2))
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)
print(arr2.transpose())

['a' 'b' '3' 'd']
4
4
(4,)
<U21
['a' 'b' '3' 'd']


In [44]:
# 2D array of characters
arr2 = np.array([['a',3,'c','d'],['e',5.2,'g','h']])
print(arr2)
print(size(arr2))
print(arr2.size)
print(arr2.shape)
print(arr2.dtype)
print(arr2.transpose())

[['a' '3' 'c' 'd']
 ['e' '5.2' 'g' 'h']]
8
8
(2, 4)
<U32
[['a' 'e']
 ['3' '5.2']
 ['c' 'g']
 ['d' 'h']]


In [39]:
# creating empty array with different data types
print(np.empty((4),dtype=int))
print(np.empty((4,3),dtype=int))
print(np.empty((4),dtype=float))
print(np.empty((4,3),dtype=float))
print(np.empty((4),dtype=str))
print(np.empty((4,3),dtype=str))
print(np.empty((4),dtype=bool))
print(np.empty((4,3),dtype=bool))

[4607182418800017408 4607182418800017408 4607182418800017408
 4607182418800017408]
[[4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]
 [4607182418800017408 4607182418800017408 4607182418800017408]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
['' '' '' '']
[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]
[ True  True  True  True]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [40]:
# creating one's array with different data types
print(np.ones((4),dtype=int))
print(np.ones((4,3),dtype=int))
print(np.ones((4),dtype=float))
print(np.ones((4,3),dtype=float))
print(np.ones((4),dtype=str))
print(np.ones((4,3),dtype=str))
print(np.ones((4),dtype=bool))
print(np.ones((4,3),dtype=bool))

[1 1 1 1]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
['1' '1' '1' '1']
[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']]
[ True  True  True  True]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [41]:
# creating zero's array with different data types
print(np.zeros((4),dtype=int))
print(np.zeros((4,3),dtype=int))
print(np.zeros((4),dtype=float))
print(np.zeros((4,3),dtype=float))
print(np.zeros((4),dtype=str))
print(np.zeros((4,3),dtype=str))
print(np.zeros((4),dtype=bool))
print(np.zeros((4,3),dtype=bool))

[0 0 0 0]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
['' '' '' '']
[['' '' '']
 ['' '' '']
 ['' '' '']
 ['' '' '']]
[False False False False]
[[False False False]
 [False False False]
 [False False False]
 [False False False]]


In [63]:
# generating series of array
arr1 = np.arange(0,10,2)
arr2 = np.arange(0,10)
arr3 = np.arange(6)
print(arr1)
print(arr2)
print(arr3)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]


In [67]:
# reshaping the array by making it multi-dimensional array
arr2 = arr2.reshape((2,5))
print(arr2)
arr3 = arr3.reshape((3,2))
print(arr3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]]


In [69]:
# reshaping the array by making it single dimensional array
arr2 = arr2.flatten()
print(arr2)
arr3 = arr3.flatten()
print(arr3)
arr2 = arr2.ravel()
print(arr2)
arr3 = arr3.ravel()
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]
